jobs:
  - name: integration-tests-compute
    plan:
      - get: fog-google-src
        resource: pull-request
        version: every
        trigger: true
      - put: pull-request
        params: {path: fog-google-src, status: pending}

      - task: full-integration-tests
        file: fog-google-src/ci/tasks/run-int.yml
        params:
          rake_task: test:compute
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_client_email: {{google_client_email}}

  - name: integration-tests-monitoring
    plan:
      - get: fog-google-src
        resource: pull-request
        version: every
        trigger: true
      - put: pull-request
        params: {path: fog-google-src, status: pending}

      - task: full-integration-tests
        file: fog-google-src/ci/tasks/run-int.yml
        params:
          rake_task: test:monitoring
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_client_email: {{google_client_email}}

  - name: integration-tests-pubsub
    plan:
      - get: fog-google-src
        resource: pull-request
        version: every
        trigger: true
      - put: pull-request
        params: {path: fog-google-src, status: pending}

      - task: full-integration-tests
        file: fog-google-src/ci/tasks/run-int.yml
        params:
          rake_task: test:pubsub
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_client_email: {{google_client_email}}

  - name: integration-tests-sql
    plan:
      - get: fog-google-src
        resource: pull-request
        version: every
        trigger: true
      - put: pull-request
        params: {path: fog-google-src, status: pending}

      - task: full-integration-tests
        file: fog-google-src/ci/tasks/run-int.yml
        params:
          rake_task: test:sql
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_client_email: {{google_client_email}}

  - name: integration-tests-storage
    plan:
      - get: fog-google-src
        resource: pull-request
        version: every
        trigger: true
      - put: pull-request
        params: {path: fog-google-src, status: pending}

      - task: full-integration-tests
        file: fog-google-src/ci/tasks/run-int.yml
        params:
          rake_task: test:storage
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_client_email: {{google_client_email}}

  - name: github-pr-aggregator
    plan:
      - get: fog-google-src
        resource: pull-request
        passed: [integration-tests-storage,
                 integration-tests-sql,
                 integration-tests-pubsub,
                 integration-tests-monitoring,
                 integration-tests-compute]
        trigger: true
        on_success:
          put: pull-request
          params:
            path: fog-google-src
            status: success
        on_failure:
          put: pull-request
          params:
            path: fog-google-src
            status: failure

resources:
  - name: pull-request
    type: pull-request
    source:
      access_token: {{github_access_token}}
      private_key: {{github_private_key}}
      label: integrate
      repo: fog/fog-google

resource_types:
  # This is a third party resource.
  # The referenced docker-image is maintained externally
  # https://github.com/jtarchie/pullrequest-resource
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr